name: proyecto-finalito

on: push

jobs:
 proyecto-finalito:
 name: Lint code base
 runs-on: ubtuntu-latest
 steps:
 - name: Checkout code
  uses: actions/checkout@v2
  
  - name: Run proyecto-finalito
    uses:  github/proyecto-finalito@v3
    enc:
      DEFAULT_BRANCH: main
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
